[build]
  command = "rm -rf node_modules package-lock.json && npm install && npm run build"
  publish = ".output/public"

[build.environment]
  NODE_VERSION = "22.22.0"
  NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
  package = "@netlify/plugin-nextjs"